server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bharatchhajer/micro-spring-cloud-discovery-config-gateway-configrepo
